POLICY = {
    "policy_version": "discovery-v1",
    "schema_version": 7,
    "source_excluded_directories": [
        ".git",
        ".discovery",
        ".venv",
        "__pycache__",
        ".pytest_cache",
        ".ruff_cache",
    ],
    "source_fingerprint_version": "sha256-path-content-mode-v1",
    "canonical_json": "python-json-sorted-utf8-v1",
    "mandatory_phase1_surfaces": [
        "request",
        "source_code",
        "tests",
        "documentation",
        "issue_history",
        "external_dependencies",
        "human_authority",
    ],
    "closure_methods_by_impact": {
        "contextual": ["evidence_gaps"],
        "material": ["contradiction", "evidence_gaps"],
        "critical": ["terminology", "snowballing", "contradiction", "evidence_gaps"],
    },
    "evidence_profiles": {
        "contextual": ["provenance"],
        "material": [
            "provenance",
            "primary_evidence",
            "semantic_verification",
            "contradiction_search",
        ],
        "critical": [
            "provenance",
            "primary_evidence",
            "semantic_verification",
            "contradiction_search",
            "falsification",
        ],
    },
    "subagent_mode": "disabled",
    "agent_count": 0,
    "agent_lease_duration": 300,
    "phase4_challenge_categories": [
        "requirements",
        "correctness",
        "data_integrity",
        "concurrency",
        "failure_recovery",
        "security",
        "compatibility",
        "performance",
        "operations",
        "testability",
        "maintainability",
        "evidence_freshness",
    ],
    "assurance_scoring_model": "structural-coverage-v1",
    "experiment_safety_policy": "disposable-local-default; restricted-when-requested",
}
